import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import {
  BookOpen, Home, Trophy, User, Volume2, ChevronRight, Check,
  Flame, Target, Play, Languages, Sparkles, ShoppingBag, Plane,
  Utensils, Users, Palette, Hash, MessageCircle, Headphones,
  Mic, Lock, RotateCcw
} from "lucide-react";
import "./styles.css";

const lessons = [
  { id:1, title:"Greetings", hi:"अभिवादन", icon:MessageCircle, words:[
    ["Hello","नमस्ते","Namaste","Greeting","नमस्ते! आप कैसे हैं?"],
    ["Good morning","सुप्रभात","Suprabhat","Morning greeting","सुप्रभात!"],
    ["Thank you","धन्यवाद","Dhanyavaad","Thanks","धन्यवाद, आपका बहुत धन्यवाद।"],
    ["Please","कृपया","Kripya","Polite request","कृपया बैठिए।"],
    ["Sorry","माफ़ कीजिए","Maaf kijiye","Apology","माफ़ कीजिए, मुझे देर हो गई।"]
  ]},
  { id:2, title:"Introduction", hi:"परिचय", icon:Users, words:[
    ["My name is...","मेरा नाम ... है","Mera naam ... hai","Introducing yourself","मेरा नाम राहुल है।"],
    ["What is your name?","आपका नाम क्या है?","Aapka naam kya hai?","Asking a name","आपका नाम क्या है?"],
    ["I am from India.","मैं भारत से हूँ।","Main Bharat se hoon.","Origin","मैं भारत से हूँ।"],
    ["Nice to meet you.","आपसे मिलकर खुशी हुई।","Aapse milkar khushi hui.","Meeting someone","आपसे मिलकर खुशी हुई।"],
    ["I am learning Hindi.","मैं हिंदी सीख रहा हूँ।","Main Hindi seekh raha hoon.","Learning","मैं हिंदी सीख रहा हूँ।"]
  ]},
  { id:3, title:"Numbers", hi:"गिनती", icon:Hash, words:[
    ["One","एक","Ek","Number 1","एक किताब"],
    ["Two","दो","Do","Number 2","दो लोग"],
    ["Three","तीन","Teen","Number 3","तीन सेब"],
    ["Ten","दस","Das","Number 10","दस रुपये"],
    ["Hundred","सौ","Sau","Number 100","सौ रुपये"]
  ]},
  { id:4, title:"Family", hi:"परिवार", icon:Users, words:[
    ["Mother","माँ","Maa","Family","मेरी माँ घर पर हैं।"],
    ["Father","पिता","Pita","Family","मेरे पिता काम करते हैं।"],
    ["Brother","भाई","Bhai","Family","मेरा भाई पढ़ता है।"],
    ["Sister","बहन","Behen","Family","मेरी बहन स्कूल जाती है।"],
    ["Family","परिवार","Parivaar","Family group","मेरा परिवार बड़ा है।"]
  ]},
  { id:5, title:"Food", hi:"खाना", icon:Utensils, words:[
    ["Water","पानी","Paani","Drink","मुझे पानी चाहिए।"],
    ["Food","खाना","Khaana","Meal/food","खाना तैयार है।"],
    ["Rice","चावल","Chaawal","Food","मुझे चावल पसंद हैं।"],
    ["Tea","चाय","Chaay","Drink","एक कप चाय, कृपया।"],
    ["Delicious","स्वादिष्ट","Swaadisht","Tasty","खाना बहुत स्वादिष्ट है।"]
  ]},
  { id:6, title:"Colors", hi:"रंग", icon:Palette, words:[
    ["Red","लाल","Laal","Color","लाल रंग सुंदर है।"],
    ["Blue","नीला","Neela","Color","आसमान नीला है।"],
    ["Green","हरा","Hara","Color","पेड़ हरा है।"],
    ["White","सफेद","Safed","Color","यह सफेद कपड़ा है।"],
    ["Black","काला","Kaala","Color","यह काला बैग है।"]
  ]},
  { id:7, title:"Daily Objects", hi:"रोज़मर्रा की चीज़ें", icon:BookOpen, words:[
    ["Book","किताब","Kitaab","Object","मेरी किताब कहाँ है?"],
    ["Phone","फ़ोन","Phone","Object","मेरा फ़ोन यहाँ है।"],
    ["Door","दरवाज़ा","Darwaaza","Object","दरवाज़ा बंद है।"],
    ["Chair","कुर्सी","Kursi","Object","कुर्सी पर बैठिए।"],
    ["Bag","बैग","Bag","Object","मेरा बैग नया है।"]
  ]},
  { id:8, title:"Shopping", hi:"खरीदारी", icon:ShoppingBag, words:[
    ["How much?","कितने का है?","Kitne ka hai?","Price question","यह कितने का है?"],
    ["Expensive","महँगा","Mehnga","High price","यह बहुत महँगा है।"],
    ["Cheap","सस्ता","Sasta","Low price","यह सस्ता है।"],
    ["Give me this.","यह मुझे दीजिए।","Yeh mujhe dijiye.","Request","यह मुझे दीजिए।"],
    ["Bill","बिल","Bill","Payment","बिल दीजिए।"]
  ]},
  { id:9, title:"Travel", hi:"यात्रा", icon:Plane, words:[
    ["Where?","कहाँ?","Kahan?","Place question","स्टेशन कहाँ है?"],
    ["Station","स्टेशन","Station","Travel place","स्टेशन पास है।"],
    ["Airport","हवाई अड्डा","Hawai adda","Travel place","हवाई अड्डा कहाँ है?"],
    ["Ticket","टिकट","Ticket","Travel document","मुझे एक टिकट चाहिए।"],
    ["Help","मदद","Madad","Assistance","मुझे मदद चाहिए।"]
  ]},
  { id:10, title:"Daily Conversation", hi:"रोज़ की बातचीत", icon:MessageCircle, words:[
    ["How are you?","आप कैसे हैं?","Aap kaise hain?","Greeting","आप कैसे हैं?"],
    ["I am fine.","मैं ठीक हूँ।","Main theek hoon.","Response","मैं ठीक हूँ।"],
    ["Where are you going?","आप कहाँ जा रहे हैं?","Aap kahan ja rahe hain?","Question","आप कहाँ जा रहे हैं?"],
    ["I don't understand.","मुझे समझ नहीं आया।","Mujhe samajh nahi aaya.","Useful phrase","मुझे समझ नहीं आया।"],
    ["See you tomorrow.","कल मिलते हैं।","Kal milte hain.","Farewell","कल मिलते हैं।"]
  ]}
];

const quizBank = [
  ["What is “Hello” in Hindi?","नमस्ते",["धन्यवाद","नमस्ते","माफ़ कीजिए","कृपया"]],
  ["What is “Water” in Hindi?","पानी",["चाय","पानी","खाना","दूध"]],
  ["What is “Mother” in Hindi?","माँ",["बहन","माँ","भाई","पिता"]],
  ["What is “One” in Hindi?","एक",["दस","दो","एक","तीन"]],
  ["What is “Book” in Hindi?","किताब",["बैग","फ़ोन","किताब","कुर्सी"]],
  ["What is “Red” in Hindi?","लाल",["हरा","नीला","लाल","सफेद"]],
  ["What is “Ticket” in Hindi?","टिकट",["स्टेशन","टिकट","मदद","बिल"]],
  ["What is “Thank you” in Hindi?","धन्यवाद",["नमस्ते","धन्यवाद","कृपया","सुप्रभात"]],
  ["What is “Family” in Hindi?","परिवार",["परिवार","दोस्त","घर","स्कूल"]],
  ["What is “How are you?” in Hindi?","आप कैसे हैं?",["आप कहाँ हैं?","आप कैसे हैं?","आपका नाम क्या है?","कल मिलते हैं।"]],
  ["What is “Father” in Hindi?","पिता",["माँ","पिता","भाई","बहन"]],
  ["What is “Blue” in Hindi?","नीला",["काला","नीला","लाल","हरा"]],
  ["What is “Airport” in Hindi?","हवाई अड्डा",["स्टेशन","बाज़ार","हवाई अड्डा","घर"]],
  ["What is “Please” in Hindi?","कृपया",["कृपया","माफ़ कीजिए","धन्यवाद","सुप्रभात"]],
  ["What is “I am fine” in Hindi?","मैं ठीक हूँ।",["मैं ठीक हूँ।","मैं जा रहा हूँ।","मुझे पानी चाहिए।","मैं भारत से हूँ।"]],
  ["What is “How much?” in Hindi?","कितने का है?",["कहाँ?","कितने का है?","कौन?","कब?"]],
  ["What is “Help” in Hindi?","मदद",["मदद","खाना","टिकट","बिल"]],
  ["What is “Good morning” in Hindi?","सुप्रभात",["शुभ रात्रि","सुप्रभात","धन्यवाद","नमस्ते"]],
  ["What is “See you tomorrow” in Hindi?","कल मिलते हैं।",["आज मिलते हैं।","कल मिलते हैं।","फिर मिलेंगे।","शुभ रात्रि।"]],
  ["What is “I am from India” in Hindi?","मैं भारत से हूँ।",["मैं हिंदी सीख रहा हूँ।","मैं भारत से हूँ।","मेरा नाम ... है।","मैं ठीक हूँ।"]],
  ["What is “Expensive” in Hindi?","महँगा",["सस्ता","महँगा","नया","पुराना"]],
  ["What is “Cheap” in Hindi?","सस्ता",["महँगा","सस्ता","अच्छा","बड़ा"]],
  ["What is “Door” in Hindi?","दरवाज़ा",["किताब","दरवाज़ा","कुर्सी","बैग"]],
  ["What is “Nice to meet you” in Hindi?","आपसे मिलकर खुशी हुई।",["आप कैसे हैं?","आपसे मिलकर खुशी हुई।","धन्यवाद।","मुझे समझ नहीं आया।"]],
  ["What is “I don't understand” in Hindi?","मुझे समझ नहीं आया।",["मुझे मदद चाहिए।","मुझे समझ नहीं आया।","मुझे पानी चाहिए।","मुझे हिंदी आती है।"]]
];

const defaultState = {
  screen:"welcome", name:"Learner", level:"Beginner", goal:10, xp:0,
  completed:[], streak:1, quizBest:0, dailyDone:0, currentLesson:1
};

function loadState(){ try { return {...defaultState, ...(JSON.parse(localStorage.getItem("hindiSikhoState"))||{})}; } catch { return defaultState; } }
function saveState(s){ localStorage.setItem("hindiSikhoState", JSON.stringify(s)); }
const LANGS = [
  {id:"en", flag:"🇬🇧", name:"English"}, {id:"ar", flag:"🇦🇪", name:"العربية"},
  {id:"fr", flag:"🇫🇷", name:"Français"}, {id:"es", flag:"🇪🇸", name:"Español"},
  {id:"de", flag:"🇩🇪", name:"Deutsch"}, {id:"ja", flag:"🇯🇵", name:"日本語"},
  {id:"ko", flag:"🇰🇷", name:"한국어"}, {id:"zh", flag:"🇨🇳", name:"中文"}
];
const ui = {
 en:{welcome:"Welcome to Hindi Sikho!",sub:"Learn Hindi naturally from your own language.",choose:"Choose your native language",chooseSub:"Select the language you understand best.",continue:"Continue",level:"Your Hindi level?",levelSub:"Choose a course for your current level.",beginner:"Beginner",intermediate:"Intermediate",advanced:"Advanced",goal:"Set your daily goal",goalSub:"How many minutes do you want to learn each day?",minutes:"minutes/day",welcomeName:"Welcome!",nameAsk:"What should we call you?",namePlaceholder:"Your name",start:"Start Hindi Journey",home:"Home",learn:"Learn",quiz:"Quiz",progress:"Progress",profile:"Profile",namaste:"Namaste 👋",dailyGoal:"Daily Goal",continueLearning:"Continue Learning",seeAll:"See all",course:"Your Course",vocabulary:"Vocabulary",words:"useful Hindi words",quickQuiz:"Quick Quiz",questions:"questions",listening:"Listening",speaking:"Speaking",coming:"Coming Soon",back:"Back",example:"Example",previous:"Previous",next:"Next",complete:"Complete Lesson",completed:"Completed",takeQuiz:"Take a Quiz",quizComplete:"Quiz Complete!",correct:"Correct! 🎉",notQuite:"Not quite.",finish:"Finish",tryAgain:"Try Again",backHome:"Back Home",yourProgress:"Your Progress",keepGoing:"Keep going — learn a little every day!",courseProgress:"Course Progress",lessons:"lessons completed",totalXP:"Total XP",dayStreak:"Day Streak",bestQuiz:"Best Quiz",learningTip:"Learning Tip",tip:"Practice 5–10 new words every day. Tap 🔊 to hear Hindi.",reset:"Reset Progress",language:"Language",daily:"Daily Goal",courseName:"Hindi for Beginners",chooseLanguage:"Choose your language",nativeToHindi:"Native language → Hindi"},
 ar:{welcome:"مرحباً بك في Hindi Sikho!",sub:"تعلّم الهندية من خلال لغتك الأم.",choose:"اختر لغتك الأم",chooseSub:"اختر اللغة التي تفهمها بشكل أفضل.",continue:"متابعة",level:"ما مستوى اللغة الهندية لديك؟",levelSub:"اختر الدورة المناسبة لمستواك.",beginner:"مبتدئ",intermediate:"متوسط",advanced:"متقدم",goal:"حدد هدفك اليومي",goalSub:"كم دقيقة تريد أن تتعلم كل يوم؟",minutes:"دقيقة/اليوم",welcomeName:"مرحباً!",nameAsk:"ما الاسم الذي نناديك به؟",namePlaceholder:"اسمك",start:"ابدأ رحلة الهندية",home:"الرئيسية",learn:"تعلّم",quiz:"اختبار",progress:"التقدم",profile:"الملف الشخصي",namaste:"ناماستي 👋",dailyGoal:"الهدف اليومي",continueLearning:"متابعة التعلم",seeAll:"عرض الكل",course:"دورتك",vocabulary:"المفردات",words:"كلمة هندية مفيدة",quickQuiz:"اختبار سريع",questions:"سؤال",listening:"الاستماع",speaking:"التحدث",coming:"قريباً",back:"رجوع",example:"مثال",previous:"السابق",next:"التالي",complete:"إكمال الدرس",completed:"مكتمل",takeQuiz:"ابدأ الاختبار",quizComplete:"اكتمل الاختبار!",correct:"صحيح! 🎉",notQuite:"ليست الإجابة الصحيحة.",finish:"إنهاء",tryAgain:"حاول مرة أخرى",backHome:"العودة للرئيسية",yourProgress:"تقدمك",keepGoing:"استمر — تعلّم قليلاً كل يوم!",courseProgress:"تقدم الدورة",lessons:"دروس مكتملة",totalXP:"إجمالي XP",dayStreak:"أيام متتالية",bestQuiz:"أفضل اختبار",learningTip:"نصيحة للتعلم",tip:"تدرّب على 5–10 كلمات جديدة يومياً. اضغط 🔊 لسماع الهندية.",reset:"إعادة ضبط التقدم",language:"اللغة",daily:"الهدف اليومي",courseName:"الهندية للمبتدئين",chooseLanguage:"اختر لغتك",nativeToHindi:"لغتك الأم → الهندية"},
 fr:{welcome:"Bienvenue sur Hindi Sikho !",sub:"Apprenez l’hindi naturellement depuis votre langue maternelle.",choose:"Choisissez votre langue maternelle",chooseSub:"Sélectionnez la langue que vous comprenez le mieux.",continue:"Continuer",level:"Quel est votre niveau d’hindi ?",levelSub:"Choisissez un cours adapté à votre niveau.",beginner:"Débutant",intermediate:"Intermédiaire",advanced:"Avancé",goal:"Définissez votre objectif quotidien",goalSub:"Combien de minutes voulez-vous apprendre chaque jour ?",minutes:"min/jour",welcomeName:"Bienvenue !",nameAsk:"Comment devons-nous vous appeler ?",namePlaceholder:"Votre nom",start:"Commencer mon parcours hindi",home:"Accueil",learn:"Apprendre",quiz:"Quiz",progress:"Progrès",profile:"Profil",namaste:"Namaste 👋",dailyGoal:"Objectif quotidien",continueLearning:"Continuer l’apprentissage",seeAll:"Tout voir",course:"Votre cours",vocabulary:"Vocabulaire",words:"mots hindi utiles",quickQuiz:"Quiz rapide",questions:"questions",listening:"Écoute",speaking:"Expression orale",coming:"Bientôt",back:"Retour",example:"Exemple",previous:"Précédent",next:"Suivant",complete:"Terminer le cours",completed:"Terminé",takeQuiz:"Faire un quiz",quizComplete:"Quiz terminé !",correct:"Correct ! 🎉",notQuite:"Ce n’est pas la bonne réponse.",finish:"Terminer",tryAgain:"Réessayer",backHome:"Accueil",yourProgress:"Votre progression",keepGoing:"Continuez — apprenez un peu chaque jour !",courseProgress:"Progression du cours",lessons:"leçons terminées",totalXP:"XP total",dayStreak:"Jours consécutifs",bestQuiz:"Meilleur quiz",learningTip:"Conseil d’apprentissage",tip:"Pratiquez 5 à 10 nouveaux mots chaque jour. Appuyez sur 🔊 pour écouter l’hindi.",reset:"Réinitialiser",language:"Langue",daily:"Objectif quotidien",courseName:"Hindi pour débutants",chooseLanguage:"Choisissez votre langue",nativeToHindi:"Langue maternelle → hindi"},
 es:{welcome:"¡Bienvenido a Hindi Sikho!",sub:"Aprende hindi desde tu propio idioma.",choose:"Elige tu idioma nativo",chooseSub:"Selecciona el idioma que entiendes mejor.",continue:"Continuar",level:"¿Cuál es tu nivel de hindi?",levelSub:"Elige un curso según tu nivel.",beginner:"Principiante",intermediate:"Intermedio",advanced:"Avanzado",goal:"Define tu objetivo diario",goalSub:"¿Cuántos minutos quieres aprender cada día?",minutes:"min/día",welcomeName:"¡Bienvenido!",nameAsk:"¿Cómo te llamamos?",namePlaceholder:"Tu nombre",start:"Comenzar mi viaje en hindi",home:"Inicio",learn:"Aprender",quiz:"Quiz",progress:"Progreso",profile:"Perfil",namaste:"Namaste 👋",dailyGoal:"Objetivo diario",continueLearning:"Continuar aprendiendo",seeAll:"Ver todo",course:"Tu curso",vocabulary:"Vocabulario",words:"palabras hindi útiles",quickQuiz:"Quiz rápido",questions:"preguntas",listening:"Escucha",speaking:"Hablar",coming:"Próximamente",back:"Atrás",example:"Ejemplo",previous:"Anterior",next:"Siguiente",complete:"Completar lección",completed:"Completado",takeQuiz:"Hacer un quiz",quizComplete:"¡Quiz completado!",correct:"¡Correcto! 🎉",notQuite:"No es la respuesta correcta.",finish:"Finalizar",tryAgain:"Intentar de nuevo",backHome:"Inicio",yourProgress:"Tu progreso",keepGoing:"Sigue — aprende un poco cada día.",courseProgress:"Progreso del curso",lessons:"lecciones completadas",totalXP:"XP total",dayStreak:"Días seguidos",bestQuiz:"Mejor quiz",learningTip:"Consejo",tip:"Practica 5–10 palabras nuevas cada día. Pulsa 🔊 para escuchar hindi.",reset:"Restablecer progreso",language:"Idioma",daily:"Objetivo diario",courseName:"Hindi para principiantes",chooseLanguage:"Elige tu idioma",nativeToHindi:"Idioma nativo → hindi"},
 de:{welcome:"Willkommen bei Hindi Sikho!",sub:"Lerne Hindi über deine eigene Sprache.",choose:"Wähle deine Muttersprache",chooseSub:"Wähle die Sprache, die du am besten verstehst.",continue:"Weiter",level:"Wie gut ist dein Hindi?",levelSub:"Wähle einen Kurs für dein Niveau.",beginner:"Anfänger",intermediate:"Mittelstufe",advanced:"Fortgeschritten",goal:"Setze dein Tagesziel",goalSub:"Wie viele Minuten möchtest du täglich lernen?",minutes:"Min./Tag",welcomeName:"Willkommen!",nameAsk:"Wie sollen wir dich nennen?",namePlaceholder:"Dein Name",start:"Hindi-Lernreise starten",home:"Start",learn:"Lernen",quiz:"Quiz",progress:"Fortschritt",profile:"Profil",namaste:"Namaste 👋",dailyGoal:"Tagesziel",continueLearning:"Weiterlernen",seeAll:"Alle anzeigen",course:"Dein Kurs",vocabulary:"Vokabeln",words:"nützliche Hindi-Wörter",quickQuiz:"Schnelles Quiz",questions:"Fragen",listening:"Hören",speaking:"Sprechen",coming:"Demnächst",back:"Zurück",example:"Beispiel",previous:"Zurück",next:"Weiter",complete:"Lektion abschließen",completed:"Abgeschlossen",takeQuiz:"Quiz starten",quizComplete:"Quiz abgeschlossen!",correct:"Richtig! 🎉",notQuite:"Das ist nicht die richtige Antwort.",finish:"Fertig",tryAgain:"Erneut versuchen",backHome:"Startseite",yourProgress:"Dein Fortschritt",keepGoing:"Bleib dran — lerne jeden Tag ein wenig!",courseProgress:"Kursfortschritt",lessons:"Lektionen abgeschlossen",totalXP:"Gesamt-XP",dayStreak:"Tages-Serie",bestQuiz:"Bestes Quiz",learningTip:"Lerntipp",tip:"Übe jeden Tag 5–10 neue Wörter. Tippe 🔊 für Hindi-Audio.",reset:"Fortschritt zurücksetzen",language:"Sprache",daily:"Tagesziel",courseName:"Hindi für Anfänger",chooseLanguage:"Wähle deine Sprache",nativeToHindi:"Muttersprache → Hindi"},
 ja:{welcome:"Hindi Sikhoへようこそ！",sub:"自分の母語を使って自然にヒンディー語を学びましょう。",choose:"母語を選択",chooseSub:"一番よく理解できる言語を選んでください。",continue:"続ける",level:"ヒンディー語のレベル",levelSub:"現在のレベルに合うコースを選択してください。",beginner:"初級",intermediate:"中級",advanced:"上級",goal:"毎日の目標を設定",goalSub:"毎日何分学習しますか？",minutes:"分/日",welcomeName:"ようこそ！",nameAsk:"お名前を教えてください",namePlaceholder:"名前",start:"ヒンディー語を始める",home:"ホーム",learn:"学習",quiz:"クイズ",progress:"進捗",profile:"プロフィール",namaste:"ナマステ 👋",dailyGoal:"毎日の目標",continueLearning:"学習を続ける",seeAll:"すべて見る",course:"コース",vocabulary:"単語",words:"役立つヒンディー語",quickQuiz:"クイッククイズ",questions:"問題",listening:"リスニング",speaking:"スピーキング",coming:"近日公開",back:"戻る",example:"例",previous:"前へ",next:"次へ",complete:"レッスン完了",completed:"完了",takeQuiz:"クイズをする",quizComplete:"クイズ完了！",correct:"正解！🎉",notQuite:"正しい答えではありません。",finish:"終了",tryAgain:"もう一度",backHome:"ホームへ",yourProgress:"進捗",keepGoing:"毎日少しずつ続けましょう！",courseProgress:"コース進捗",lessons:"レッスン完了",totalXP:"合計XP",dayStreak:"連続日数",bestQuiz:"最高クイズ",learningTip:"学習のコツ",tip:"毎日5〜10語を練習。🔊でヒンディー語を聞けます。",reset:"進捗をリセット",language:"言語",daily:"毎日の目標",courseName:"初心者向けヒンディー語",chooseLanguage:"言語を選択",nativeToHindi:"母語 → ヒンディー語"},
 ko:{welcome:"Hindi Sikho에 오신 것을 환영합니다!",sub:"모국어로 자연스럽게 힌디어를 배워보세요.",choose:"모국어 선택",chooseSub:"가장 잘 이해하는 언어를 선택하세요.",continue:"계속",level:"힌디어 수준은?",levelSub:"현재 수준에 맞는 과정을 선택하세요.",beginner:"초급",intermediate:"중급",advanced:"고급",goal:"일일 목표 설정",goalSub:"매일 몇 분 학습할까요?",minutes:"분/일",welcomeName:"환영합니다!",nameAsk:"어떻게 불러드릴까요?",namePlaceholder:"이름",start:"힌디어 학습 시작",home:"홈",learn:"학습",quiz:"퀴즈",progress:"진도",profile:"프로필",namaste:"나마스테 👋",dailyGoal:"일일 목표",continueLearning:"학습 계속하기",seeAll:"전체 보기",course:"내 코스",vocabulary:"단어",words:"유용한 힌디어 단어",quickQuiz:"빠른 퀴즈",questions:"문제",listening:"듣기",speaking:"말하기",coming:"준비 중",back:"뒤로",example:"예문",previous:"이전",next:"다음",complete:"레슨 완료",completed:"완료",takeQuiz:"퀴즈 풀기",quizComplete:"퀴즈 완료!",correct:"정답! 🎉",notQuite:"정답이 아닙니다.",finish:"완료",tryAgain:"다시 시도",backHome:"홈으로",yourProgress:"학습 진도",keepGoing:"매일 조금씩 계속하세요!",courseProgress:"코스 진도",lessons:"레슨 완료",totalXP:"총 XP",dayStreak:"연속 학습",bestQuiz:"최고 퀴즈",learningTip:"학습 팁",tip:"매일 5~10개의 새 단어를 연습하세요. 🔊를 눌러 힌디어를 들어보세요.",reset:"진도 초기화",language:"언어",daily:"일일 목표",courseName:"힌디어 초급",chooseLanguage:"언어 선택",nativeToHindi:"모국어 → 힌디어"},
 zh:{welcome:"欢迎来到 Hindi Sikho！",sub:"用你的母语自然地学习印地语。",choose:"选择你的母语",chooseSub:"选择你最熟悉的语言。",continue:"继续",level:"你的印地语水平？",levelSub:"选择适合你当前水平的课程。",beginner:"初级",intermediate:"中级",advanced:"高级",goal:"设置每日目标",goalSub:"你每天想学习多少分钟？",minutes:"分钟/天",welcomeName:"欢迎！",nameAsk:"我们应该怎么称呼你？",namePlaceholder:"你的名字",start:"开始印地语学习",home:"首页",learn:"学习",quiz:"测验",progress:"进度",profile:"个人资料",namaste:"Namaste 👋",dailyGoal:"每日目标",continueLearning:"继续学习",seeAll:"查看全部",course:"你的课程",vocabulary:"词汇",words:"实用印地语单词",quickQuiz:"快速测验",questions:"题目",listening:"听力",speaking:"口语",coming:"即将推出",back:"返回",example:"例句",previous:"上一题",next:"下一题",complete:"完成课程",completed:"已完成",takeQuiz:"开始测验",quizComplete:"测验完成！",correct:"正确！🎉",notQuite:"答案不正确。",finish:"完成",tryAgain:"再试一次",backHome:"返回首页",yourProgress:"你的进度",keepGoing:"坚持下去——每天学一点！",courseProgress:"课程进度",lessons:"课已完成",totalXP:"总 XP",dayStreak:"连续学习",bestQuiz:"最佳测验",learningTip:"学习提示",tip:"每天练习5–10个新词。点击🔊听印地语发音。",reset:"重置进度",language:"语言",daily:"每日目标",courseName:"印地语入门",chooseLanguage:"选择语言",nativeToHindi:"母语 → 印地语"}
};
const wordNative = {
 en:{"Hello":"Hello","Good morning":"Good morning","Thank you":"Thank you","Please":"Please","Sorry":"Sorry","My name is...":"My name is...","What is your name?":"What is your name?","I am from India.":"I am from India.","Nice to meet you.":"Nice to meet you.","I am learning Hindi.":"I am learning Hindi.","One":"One","Two":"Two","Three":"Three","Ten":"Ten","Hundred":"Hundred","Mother":"Mother","Father":"Father","Brother":"Brother","Sister":"Sister","Family":"Family","Water":"Water","Food":"Food","Rice":"Rice","Tea":"Tea","Delicious":"Delicious","Red":"Red","Blue":"Blue","Green":"Green","White":"White","Black":"Black","Book":"Book","Phone":"Phone","Door":"Door","Chair":"Chair","Bag":"Bag","How much?":"How much?","Expensive":"Expensive","Cheap":"Cheap","Give me this.":"Give me this.","Bill":"Bill","Where?":"Where?","Station":"Station","Airport":"Airport","Ticket":"Ticket","Help":"Help","How are you?":"How are you?","I am fine.":"I am fine.","Where are you going?":"Where are you going?","I don't understand.":"I don't understand.","See you tomorrow.":"See you tomorrow."},
 ar:{"Hello":"مرحباً","Good morning":"صباح الخير","Thank you":"شكراً","Please":"من فضلك","Sorry":"آسف","My name is...":"اسمي...","What is your name?":"ما اسمك؟","I am from India.":"أنا من الهند.","Nice to meet you.":"سعيد بلقائك.","I am learning Hindi.":"أنا أتعلم الهندية.","One":"واحد","Two":"اثنان","Three":"ثلاثة","Ten":"عشرة","Hundred":"مئة","Mother":"الأم","Father":"الأب","Brother":"الأخ","Sister":"الأخت","Family":"العائلة","Water":"ماء","Food":"طعام","Rice":"أرز","Tea":"شاي","Delicious":"لذيذ","Red":"أحمر","Blue":"أزرق","Green":"أخضر","White":"أبيض","Black":"أسود","Book":"كتاب","Phone":"هاتف","Door":"باب","Chair":"كرسي","Bag":"حقيبة","How much?":"كم السعر؟","Expensive":"غالي","Cheap":"رخيص","Give me this.":"أعطني هذا.","Bill":"الفاتورة","Where?":"أين؟","Station":"محطة","Airport":"مطار","Ticket":"تذكرة","Help":"مساعدة","How are you?":"كيف حالك؟","I am fine.":"أنا بخير.","Where are you going?":"إلى أين تذهب؟","I don't understand.":"لا أفهم.","See you tomorrow.":"أراك غداً."},
 fr:{"Hello":"Bonjour","Good morning":"Bonjour","Thank you":"Merci","Please":"S’il vous plaît","Sorry":"Désolé","My name is...":"Je m’appelle...","What is your name?":"Comment vous appelez-vous ?","I am from India.":"Je viens d’Inde.","Nice to meet you.":"Enchanté(e).","I am learning Hindi.":"J’apprends l’hindi.","One":"Un","Two":"Deux","Three":"Trois","Ten":"Dix","Hundred":"Cent","Mother":"Mère","Father":"Père","Brother":"Frère","Sister":"Sœur","Family":"Famille","Water":"Eau","Food":"Nourriture","Rice":"Riz","Tea":"Thé","Delicious":"Délicieux","Red":"Rouge","Blue":"Bleu","Green":"Vert","White":"Blanc","Black":"Noir","Book":"Livre","Phone":"Téléphone","Door":"Porte","Chair":"Chaise","Bag":"Sac","How much?":"Combien ?","Expensive":"Cher","Cheap":"Pas cher","Give me this.":"Donnez-moi ceci.","Bill":"Facture","Where?":"Où ?","Station":"Gare","Airport":"Aéroport","Ticket":"Billet","Help":"Aide","How are you?":"Comment allez-vous ?","I am fine.":"Je vais bien.","Where are you going?":"Où allez-vous ?","I don't understand.":"Je ne comprends pas.","See you tomorrow.":"À demain."},
 es:{"Hello":"Hola","Good morning":"Buenos días","Thank you":"Gracias","Please":"Por favor","Sorry":"Lo siento","My name is...":"Me llamo...","What is your name?":"¿Cómo te llamas?","I am from India.":"Soy de India.","Nice to meet you.":"Mucho gusto.","I am learning Hindi.":"Estoy aprendiendo hindi.","One":"Uno","Two":"Dos","Three":"Tres","Ten":"Diez","Hundred":"Cien","Mother":"Madre","Father":"Padre","Brother":"Hermano","Sister":"Hermana","Family":"Familia","Water":"Agua","Food":"Comida","Rice":"Arroz","Tea":"Té","Delicious":"Delicioso","Red":"Rojo","Blue":"Azul","Green":"Verde","White":"Blanco","Black":"Negro","Book":"Libro","Phone":"Teléfono","Door":"Puerta","Chair":"Silla","Bag":"Bolso","How much?":"¿Cuánto cuesta?","Expensive":"Caro","Cheap":"Barato","Give me this.":"Dame esto.","Bill":"Cuenta","Where?":"¿Dónde?","Station":"Estación","Airport":"Aeropuerto","Ticket":"Billete","Help":"Ayuda","How are you?":"¿Cómo estás?","I am fine.":"Estoy bien.","Where are you going?":"¿Adónde vas?","I don't understand.":"No entiendo.","See you tomorrow.":"Hasta mañana."},
 de:{"Hello":"Hallo","Good morning":"Guten Morgen","Thank you":"Danke","Please":"Bitte","Sorry":"Entschuldigung","My name is...":"Mein Name ist...","What is your name?":"Wie heißt du?","I am from India.":"Ich komme aus Indien.","Nice to meet you.":"Schön, dich kennenzulernen.","I am learning Hindi.":"Ich lerne Hindi.","One":"Eins","Two":"Zwei","Three":"Drei","Ten":"Zehn","Hundred":"Hundert","Mother":"Mutter","Father":"Vater","Brother":"Bruder","Sister":"Schwester","Family":"Familie","Water":"Wasser","Food":"Essen","Rice":"Reis","Tea":"Tee","Delicious":"Lecker","Red":"Rot","Blue":"Blau","Green":"Grün","White":"Weiß","Black":"Schwarz","Book":"Buch","Phone":"Telefon","Door":"Tür","Chair":"Stuhl","Bag":"Tasche","How much?":"Wie viel?","Expensive":"Teuer","Cheap":"Günstig","Give me this.":"Gib mir das.","Bill":"Rechnung","Where?":"Wo?","Station":"Bahnhof","Airport":"Flughafen","Ticket":"Fahrkarte","Help":"Hilfe","How are you?":"Wie geht es dir?","I am fine.":"Mir geht es gut.","Where are you going?":"Wohin gehst du?","I don't understand.":"Ich verstehe nicht.","See you tomorrow.":"Bis morgen."},
 ja:{"Hello":"こんにちは","Good morning":"おはようございます","Thank you":"ありがとう","Please":"お願いします","Sorry":"すみません","My name is...":"私の名前は…です","What is your name?":"お名前は何ですか？","I am from India.":"私はインド出身です。","Nice to meet you.":"はじめまして。","I am learning Hindi.":"ヒンディー語を勉強しています。","One":"一","Two":"二","Three":"三","Ten":"十","Hundred":"百","Mother":"母","Father":"父","Brother":"兄弟","Sister":"姉妹","Family":"家族","Water":"水","Food":"食べ物","Rice":"ご飯","Tea":"お茶","Delicious":"おいしい","Red":"赤","Blue":"青","Green":"緑","White":"白","Black":"黒","Book":"本","Phone":"電話","Door":"ドア","Chair":"椅子","Bag":"バッグ","How much?":"いくらですか？","Expensive":"高い","Cheap":"安い","Give me this.":"これをください。","Bill":"お会計","Where?":"どこ？","Station":"駅","Airport":"空港","Ticket":"チケット","Help":"助け","How are you?":"お元気ですか？","I am fine.":"元気です。","Where are you going?":"どこへ行きますか？","I don't understand.":"分かりません。","See you tomorrow.":"また明日。"},
 ko:{"Hello":"안녕하세요","Good morning":"좋은 아침입니다","Thank you":"감사합니다","Please":"부탁합니다","Sorry":"죄송합니다","My name is...":"제 이름은 …입니다","What is your name?":"이름이 뭐예요?","I am from India.":"저는 인도에서 왔어요.","Nice to meet you.":"만나서 반가워요.","I am learning Hindi.":"저는 힌디어를 배우고 있어요.","One":"하나","Two":"둘","Three":"셋","Ten":"열","Hundred":"백","Mother":"어머니","Father":"아버지","Brother":"형제","Sister":"자매","Family":"가족","Water":"물","Food":"음식","Rice":"밥","Tea":"차","Delicious":"맛있어요","Red":"빨강","Blue":"파랑","Green":"초록","White":"흰색","Black":"검정","Book":"책","Phone":"전화","Door":"문","Chair":"의자","Bag":"가방","How much?":"얼마예요?","Expensive":"비싸요","Cheap":"싸요","Give me this.":"이것 주세요.","Bill":"계산서","Where?":"어디예요?","Station":"역","Airport":"공항","Ticket":"표","Help":"도움","How are you?":"어떻게 지내세요?","I am fine.":"잘 지내요.","Where are you going?":"어디 가세요?","I don't understand.":"이해하지 못했어요.","See you tomorrow.":"내일 만나요."},
 zh:{"Hello":"你好","Good morning":"早上好","Thank you":"谢谢","Please":"请","Sorry":"对不起","My name is...":"我的名字是……","What is your name?":"你叫什么名字？","I am from India.":"我来自印度。","Nice to meet you.":"很高兴认识你。","I am learning Hindi.":"我正在学习印地语。","One":"一","Two":"二","Three":"三","Ten":"十","Hundred":"一百","Mother":"妈妈","Father":"爸爸","Brother":"兄弟","Sister":"姐妹","Family":"家庭","Water":"水","Food":"食物","Rice":"米饭","Tea":"茶","Delicious":"美味","Red":"红色","Blue":"蓝色","Green":"绿色","White":"白色","Black":"黑色","Book":"书","Phone":"手机","Door":"门","Chair":"椅子","Bag":"包","How much?":"多少钱？","Expensive":"贵","Cheap":"便宜","Give me this.":"给我这个。","Bill":"账单","Where?":"哪里？","Station":"车站","Airport":"机场","Ticket":"票","Help":"帮助","How are you?":"你好吗？","I am fine.":"我很好。","Where are you going?":"你要去哪里？","I don't understand.":"我不明白。","See you tomorrow.":"明天见。"}
};
const lessonTitles={
 en:{"Greetings":"Greetings","Introduction":"Introduction","Numbers":"Numbers","Family":"Family","Food":"Food","Colors":"Colors","Daily Objects":"Daily Objects","Shopping":"Shopping","Travel":"Travel","Daily Conversation":"Daily Conversation"},
 ar:{"Greetings":"التحيات","Introduction":"التعريف بالنفس","Numbers":"الأرقام","Family":"العائلة","Food":"الطعام","Colors":"الألوان","Daily Objects":"الأشياء اليومية","Shopping":"التسوق","Travel":"السفر","Daily Conversation":"المحادثة اليومية"},
 fr:{"Greetings":"Salutations","Introduction":"Présentation","Numbers":"Nombres","Family":"Famille","Food":"Nourriture","Colors":"Couleurs","Daily Objects":"Objets du quotidien","Shopping":"Achats","Travel":"Voyage","Daily Conversation":"Conversation quotidienne"},
 es:{"Greetings":"Saludos","Introduction":"Presentación","Numbers":"Números","Family":"Familia","Food":"Comida","Colors":"Colores","Daily Objects":"Objetos cotidianos","Shopping":"Compras","Travel":"Viajes","Daily Conversation":"Conversación diaria"},
 de:{"Greetings":"Begrüßungen","Introduction":"Vorstellung","Numbers":"Zahlen","Family":"Familie","Food":"Essen","Colors":"Farben","Daily Objects":"Alltagsgegenstände","Shopping":"Einkaufen","Travel":"Reisen","Daily Conversation":"Alltagsgespräch"},
 ja:{"Greetings":"あいさつ","Introduction":"自己紹介","Numbers":"数字","Family":"家族","Food":"食べ物","Colors":"色","Daily Objects":"日用品","Shopping":"買い物","Travel":"旅行","Daily Conversation":"日常会話"},
 ko:{"Greetings":"인사","Introduction":"소개","Numbers":"숫자","Family":"가족","Food":"음식","Colors":"색깔","Daily Objects":"일상용품","Shopping":"쇼핑","Travel":"여행","Daily Conversation":"일상 대화"},
 zh:{"Greetings":"问候","Introduction":"自我介绍","Numbers":"数字","Family":"家庭","Food":"食物","Colors":"颜色","Daily Objects":"日常用品","Shopping":"购物","Travel":"旅行","Daily Conversation":"日常对话"}
};
function tr(lang,key){return (ui[lang]&&ui[lang][key])||ui.en[key]||key}
function nativeText(lang,text){return (wordNative[lang]&&wordNative[lang][text])||text}
function localizedLessons(lang){return lessons.map(l=>({...l,title:(lessonTitles[lang]&&lessonTitles[lang][l.title])||l.title,words:l.words.map(w=>[nativeText(lang,w[0]),w[1],w[2],nativeText(lang,w[3]),w[4]])}))}
function localizedQuiz(lang){return quizBank.map(item=>{const source=item[0].replace(/^What is “/,'').replace(/” in Hindi\?$/,''); const sourceText=nativeText(lang,source); return [`${sourceText} → Hindi`,item[1],item[2]]})}
function getSpeechLang(lang){return ({en:"en-US",ar:"ar-SA",fr:"fr-FR",es:"es-ES",de:"de-DE",ja:"ja-JP",ko:"ko-KR",zh:"zh-CN"})[lang]||"en-US"}
function speak(text,lang="hi"){if("speechSynthesis" in window){window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang==="hi"?"hi-IN":getSpeechLang(lang);u.rate=.82;window.speechSynthesis.speak(u)}}

function App(){
 const [state,setState]=useState(loadState); const [screen,setScreen]=useState(state.screen||"welcome"); const [selectedLesson,setSelectedLesson]=useState(state.currentLesson||1);
 useEffect(()=>saveState({...state,screen}),[state,screen]);
 const update=patch=>setState(s=>({...s,...patch})); const go=s=>{setScreen(s);window.scrollTo({top:0,behavior:"smooth"})}; const lang=state.language||"en"; const L=localizedLessons(lang);
 if(screen==="welcome")return <Welcome onStart={()=>go("language")} lang={lang}/>;
 if(screen==="language")return <Language value={lang} onNext={v=>{update({language:v});go("level")}}/>;
 if(screen==="level")return <Level lang={lang} onNext={v=>{update({level:v});go("goal")}}/>;
 if(screen==="goal")return <Goal lang={lang} onNext={v=>{update({goal:v});go("profileSetup")}}/>;
 if(screen==="profileSetup")return <ProfileSetup lang={lang} onNext={name=>{update({name:name||"Learner"});go("home")}}/>;
 if(screen==="lesson")return <Lesson lesson={L.find(x=>x.id===selectedLesson)} state={state} update={update} go={go} lang={lang}/>;
 if(screen==="quiz")return <Quiz state={state} update={update} go={go} lang={lang}/>;
 if(screen==="vocabulary")return <Vocabulary state={state} go={go} lang={lang} lessons={L}/>;
 if(screen==="progress")return <Progress state={state} go={go} lang={lang}/>;
 if(screen==="profile")return <Profile state={state} update={update} go={go} lang={lang}/>;
 return <HomePage state={state} go={go} lessons={L} selectedLesson={selectedLesson} setSelectedLesson={setSelectedLesson} lang={lang}/>;
}
function Shell({children,state,go,active="home",lang}){const nav=[[Home,"home","home"],[BookOpen,"learn","home"],[Trophy,"quiz","quiz"],[Target,"progress","progress"],[User,"profile","profile"]];return <div className="app-shell"><header className="topbar"><div className="brand" onClick={()=>go("home")}><span className="brand-mark">हि</span><div><b>Hindi Sikho</b><small>Apni Language Se Hindi Sikho</small></div></div><button className="icon-btn" onClick={()=>go("profile")}><User size={19}/></button></header><main>{children}</main><nav className="bottom-nav">{nav.map(([I,k,s])=><button key={k} className={active===s?"nav-active":""} onClick={()=>go(s)}><I size={20}/><span>{tr(lang,k)}</span></button>)}</nav></div>}
function Welcome({onStart,lang}){return <div className="onboard"><div className="hero-logo">हि</div><h1>{tr(lang,"welcome")}</h1><p className="muted">{tr(lang,"sub")}</p><div className="welcome-card"><Languages size={28}/><h2>Hindi सीखना आसान है!</h2><p>{tr(lang,"nativeToHindi")}</p></div><button className="primary wide" onClick={onStart}>{tr(lang,"start")} <ChevronRight/></button><small className="muted">8 native languages • Hindi target</small></div>}
function Language({value,onNext}){return <div className="onboard"><div className="step">1 / 3</div><h1>{tr(value,"chooseLanguage")}</h1><p className="muted">{tr(value,"chooseSub")}</p><div className="language-grid">{LANGS.map(x=><button key={x.id} className={"lang "+(value===x.id?"selected":"")} onClick={()=>onNext(x.id)}><span>{x.flag}</span><div><b>{x.name}</b><small>{x.name} → Hindi</small></div>{value===x.id&&<Check/>}</button>)}</div><button className="primary wide" onClick={()=>onNext(value)}>{tr(value,"continue")} <ChevronRight/></button></div>}
function Level({onNext,lang}){const [v,setV]=useState("Beginner");const labels={Beginner:"beginner",Intermediate:"intermediate",Advanced:"advanced"};return <div className="onboard"><div className="step">2 / 3</div><h1>{tr(lang,"level")}</h1><p className="muted">{tr(lang,"levelSub")}</p>{["Beginner","Intermediate","Advanced"].map(x=><button key={x} className={"choice "+(v===x?"selected":"")} onClick={()=>setV(x)}><div><b>{tr(lang,labels[x])}</b><small>{x==="Beginner"?"Start from zero":x==="Intermediate"?"I know some Hindi":"I know Hindi well"}</small></div>{v===x&&<Check/>}</button>)}<button className="primary wide" onClick={()=>onNext(v)}>{tr(lang,"continue")} <ChevronRight/></button></div>}
function Goal({onNext,lang}){const [v,setV]=useState(10);return <div className="onboard"><div className="step">3 / 3</div><h1>{tr(lang,"goal")}</h1><p className="muted">{tr(lang,"goalSub")}</p>{[5,10,15,20].map(x=><button key={x} className={"goal "+(v===x?"selected":"")} onClick={()=>setV(x)}><b>{x}</b><span>{tr(lang,"minutes")}</span></button>)}<button className="primary wide" onClick={()=>onNext(v)}>{tr(lang,"continue")} <ChevronRight/></button></div>}
function ProfileSetup({onNext,lang}){const [n,setN]=useState("");return <div className="onboard"><div className="hero-logo small">हि</div><h1>{tr(lang,"welcomeName")}</h1><p className="muted">{tr(lang,"nameAsk")}</p><input className="input" value={n} onChange={e=>setN(e.target.value)} placeholder={tr(lang,"namePlaceholder")} maxLength={30}/><button className="primary wide" onClick={()=>onNext(n)}>{tr(lang,"start")} <Play size={18}/></button></div>}
function HomePage({state,go,lessons,selectedLesson,setSelectedLesson,lang}){const completed=state.completed.length;const next=lessons.find(x=>!state.completed.includes(x.id))||lessons[lessons.length-1];return <Shell state={state} go={go} lang={lang}><section className="container"><div className="greeting"><div><span className="muted">{tr(lang,"namaste")}</span><h2>{state.name}</h2></div><div className="streak"><Flame size={18}/><b>{state.streak}</b><small>day</small></div></div><div className="stats"><div><Sparkles/><b>{state.xp}</b><small>XP</small></div><div><Flame/><b>{state.streak}</b><small>{tr(lang,"dayStreak")}</small></div><div><Trophy/><b>{state.quizBest}%</b><small>{tr(lang,"bestQuiz")}</small></div></div><div className="goal-card"><div><b>{tr(lang,"dailyGoal")}</b><span>{Math.min(state.dailyDone,state.goal)} / {state.goal} min</span></div><div className="progress"><i style={{width:`${Math.min(100,(state.dailyDone/state.goal)*100)}%`}}/></div></div><div className="section-head"><h3>{tr(lang,"continueLearning")}</h3><button onClick={()=>go("home")}>{tr(lang,"seeAll")}</button></div><div className="continue-card" onClick={()=>{setSelectedLesson(next.id);go("lesson")}}><div className="lesson-icon">{(()=>{const Icon=next.icon;return <Icon size={25}/>})()}</div><div className="grow"><small>Lesson {next.id}</small><b>{next.title}</b><span>{next.hi} • {next.words.length} words</span></div><ChevronRight/></div><div className="section-head"><h3>{tr(lang,"course")}</h3><span className="muted">{completed}/{lessons.length}</span></div><div className="course-list">{lessons.map(l=>{const done=state.completed.includes(l.id);return <button key={l.id} className={"lesson-row "+(done?"done":"")} onClick={()=>{setSelectedLesson(l.id);go("lesson")}}><span className="mini-icon">{(()=>{const Icon=l.icon;return <Icon size={18}/>})()}</span><div className="grow"><b>{l.id}. {l.title}</b><small>{l.hi}</small></div>{done?<span className="check"><Check size={15}/></span>:<ChevronRight size={18}/>}</button>})}</div><div className="feature-grid"><button onClick={()=>go("vocabulary")}><BookOpen/><b>{tr(lang,"vocabulary")}</b><small>50+ {tr(lang,"words")}</small></button><button onClick={()=>go("quiz")}><Trophy/><b>{tr(lang,"quickQuiz")}</b><small>25 {tr(lang,"questions")}</small></button><button><Headphones/><b>{tr(lang,"listening")}</b><small>{tr(lang,"coming")}</small></button><button><Mic/><b>{tr(lang,"speaking")}</b><small>{tr(lang,"coming")}</small></button></div></section></Shell>}
function Lesson({lesson,state,update,go,lang}){const [idx,setIdx]=useState(0);const [done,setDone]=useState(false);const w=lesson.words[idx];const completed=state.completed.includes(lesson.id);const finish=()=>{if(!completed)update({completed:[...state.completed,lesson.id],xp:state.xp+20,dailyDone:state.dailyDone+5,currentLesson:Math.min(10,lesson.id+1)});setDone(true)};return <Shell state={state} go={go} lang={lang}><section className="container"><button className="back" onClick={()=>go("home")}>← {tr(lang,"back")}</button><div className="lesson-header"><span>Lesson {lesson.id}</span><h2>{lesson.title}</h2><p>{lesson.hi}</p></div><div className="word-card"><div className="word-top"><span className="tag">Vocabulary {idx+1}/{lesson.words.length}</span><button className="sound" onClick={()=>speak(w[1])}><Volume2/></button></div><h1>{w[1]}</h1><h3>{w[2]}</h3><p>{w[0]} • {w[3]}</p><div className="example"><small>{tr(lang,"example")}</small><b>{w[4]}</b><button onClick={()=>speak(w[4])}><Volume2 size={17}/></button></div></div><div className="dots">{lesson.words.map((_,i)=><i key={i} className={i===idx?"active":""}/>)}</div><div className="lesson-actions">{idx>0&&<button className="secondary" onClick={()=>setIdx(idx-1)}>{tr(lang,"previous")}</button>}{idx<lesson.words.length-1?<button className="primary grow" onClick={()=>setIdx(idx+1)}>{tr(lang,"next")} <ChevronRight/></button>:<button className="primary grow" onClick={finish}>{completed||done?<><Check/> {tr(lang,"completed")}</>:<>{tr(lang,"complete")} <Check/></>}</button>}</div>{done&&<div className="success"><Sparkles/> +20 XP earned!</div>}<button className="outline wide" onClick={()=>go("quiz")}>{tr(lang,"takeQuiz")} <Trophy size={18}/></button></section></Shell>}
function Vocabulary({state,go,lang,lessons}){const all=lessons.flatMap(l=>l.words.map(w=>({l:l.id,w})));return <Shell state={state} go={go} active="home" lang={lang}><section className="container"><div className="page-title"><div><h2>{tr(lang,"vocabulary")}</h2><p>50+ {tr(lang,"words")}</p></div><BookOpen/></div><div className="vocab-list">{all.map((x,i)=><div className="vocab" key={i}><div className="grow"><b>{x.w[1]}</b><strong>{x.w[2]}</strong><small>{x.w[0]} • {x.w[3]}</small><span>{x.w[4]}</span></div><button className="sound" onClick={()=>speak(x.w[1])}><Volume2 size={18}/></button></div>)}</div></section></Shell>}
function Quiz({state,update,go,lang}){const bank=localizedQuiz(lang);const [q,setQ]=useState(0),[score,setScore]=useState(0),[selected,setSelected]=useState(null),[finished,setFinished]=useState(false);const item=bank[q];const choose=v=>{if(selected)return;setSelected(v);if(v===item[1])setScore(s=>s+1)};const next=()=>{if(q===bank.length-1){const final=score+(selected===item[1]?1:0);const pct=Math.round((final/bank.length)*100);update({quizBest:Math.max(state.quizBest,pct),xp:state.xp+Math.round(pct/5)});setScore(final);setFinished(true)}else{setQ(q+1);setSelected(null)}};if(finished)return <Shell state={state} go={go} active="quiz" lang={lang}><section className="container center"><div className="result-icon"><Trophy/></div><h1>{tr(lang,"quizComplete")}</h1><p className="muted">{bank.length} {tr(lang,"questions")}</p><div className="score"><b>{Math.round((score/bank.length)*100)}%</b><span>{score}/{bank.length} correct</span></div><button className="primary wide" onClick={()=>{setQ(0);setScore(0);setSelected(null);setFinished(false)}}><RotateCcw/> {tr(lang,"tryAgain")}</button><button className="outline wide" onClick={()=>go("home")}>{tr(lang,"backHome")}</button></section></Shell>;return <Shell state={state} go={go} active="quiz" lang={lang}><section className="container"><button className="back" onClick={()=>go("home")}>← {tr(lang,"backHome")}</button><div className="quiz-progress"><span>{q+1} / {bank.length}</span><div className="progress"><i style={{width:`${((q+1)/bank.length)*100}%`}}/></div></div><div className="quiz-card"><span className="tag">{tr(lang,"nativeToHindi")}</span><h2>{item[0]}</h2><div className="answers">{item[2].map(a=><button key={a} className={selected?(a===item[1]?"correct":a===selected?"wrong":""):""} onClick={()=>choose(a)}>{a}{selected&&a===item[1]&&<Check/>}</button>)}</div></div>{selected&&<div className={"feedback "+(selected===item[1]?"good":"bad")}>{selected===item[1]?tr(lang,"correct"):`${tr(lang,"notQuite")} सही answer: ${item[1]}`}</div>}<button className="primary wide" disabled={!selected} onClick={next}>{q===bank.length-1?tr(lang,"finish"):tr(lang,"next")} <ChevronRight/></button></section></Shell>}
function Progress({state,go,lang}){const pct=Math.round((state.completed.length/10)*100);return <Shell state={state} go={go} active="progress" lang={lang}><section className="container"><div className="page-title"><div><h2>{tr(lang,"yourProgress")}</h2><p>{tr(lang,"keepGoing")}</p></div><Target/></div><div className="big-progress"><div className="ring"><b>{pct}%</b></div><div><b>{tr(lang,"courseProgress")}</b><span>{state.completed.length} / 10 {tr(lang,"lessons")}</span></div></div><div className="progress-grid"><div><Sparkles/><b>{state.xp}</b><small>{tr(lang,"totalXP")}</small></div><div><Flame/><b>{state.streak}</b><small>{tr(lang,"dayStreak")}</small></div><div><Trophy/><b>{state.quizBest}%</b><small>{tr(lang,"bestQuiz")}</small></div><div><Check/><b>{state.completed.length}</b><small>{tr(lang,"lessons")}</small></div></div><div className="tip"><Sparkles/><div><b>{tr(lang,"learningTip")}</b><p>{tr(lang,"tip")}</p></div></div></section></Shell>}
function Profile({state,go,lang}){const reset=()=>{if(confirm("Reset progress?")){localStorage.removeItem("hindiSikhoState");location.reload()}};const ln=LANGS.find(x=>x.id===(state.language||"en"));return <Shell state={state} go={go} active="profile" lang={lang}><section className="container"><div className="profile-head"><div className="avatar">{state.name.slice(0,1).toUpperCase()}</div><h2>{state.name}</h2><p>{state.level} • {ln?.name} → Hindi</p></div><div className="profile-card"><div><b>{tr(lang,"daily")}</b><span>{state.goal} {tr(lang,"minutes")}</span></div><div><b>{tr(lang,"course")}</b><span>{tr(lang,"courseName")}</span></div><div><b>{tr(lang,"language")}</b><span>{ln?.name} → Hindi</span></div></div><button className="outline wide" onClick={()=>go("home")}>{tr(lang,"continueLearning")}</button><button className="danger wide" onClick={reset}>{tr(lang,"reset")}</button><p className="muted center small">Hindi Sikho • Native language learning</p></section></Shell>}

createRoot(document.getElementById("root")).render(<App/>);
